name: Metrics
  
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      # Overall metrics
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Pacific/Auckland
          filename: .github/yuri-norwood-metrics.svg
          base: header

          # Show isometric commit calendar
          plugin_isocalendar: yes

          # Show coding habbits
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes

      # Dotfile specific metrics
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Pacific/Auckland
          filename: .github/dotfiles-metrics.svg
          base: header
          query: '{"repo":"dotfiles"}'

          # Show followup to issues and pulls
          plugin_followup: yes

          # Show license details
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
