name: Metrics
  
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          plugin_licenses: yes
          plugin_licenses_setup: dotfiles scripts fortunes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes
