name: Metrics
  
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Pacific/Auckland

          # Show license details
          plugin_licenses: yes
          plugin_licenses_setup: dotfiles scripts fortunes
          plugin_licenses_ratio: yes
          plugin_licenses_legal: yes

          # Show isometric commit calendar
          plugin_isocalendar: yes

          # Show coding habbits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
